"""
pdf_report.py
-------------
Builds a downloadable PDF verification report for a single check,
using reportlab. Returns an in-memory BytesIO buffer (no temp files).
"""

import json
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

RISK_COLORS = {
    "Low": colors.HexColor("#22c55e"),
    "Medium": colors.HexColor("#f59e0b"),
    "High": colors.HexColor("#ef4444"),
}


def build_pdf_report(check_row) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#4f46e5"), fontSize=20,
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#4338ca"), spaceBefore=12,
    )
    body_style = styles["BodyText"]

    risk_level = check_row["risk_level"]
    risk_color = RISK_COLORS.get(risk_level, colors.grey)

    elements = []
    elements.append(Paragraph("Job/Internship Verification Report", title_style))
    elements.append(Paragraph("AI-Based Fake Internship &amp; Job Detection System", body_style))
    elements.append(Spacer(1, 10 * mm))

    meta_table_data = [
        ["Generated on", check_row["created_at"]],
        ["Company name", check_row["company_name"] or "Not provided"],
        ["Company URL", check_row["company_url"] or "Not provided"],
        ["Salary / stipend", check_row["salary_text"] or "Not provided"],
        ["Contact email", check_row["contact_email"] or "Not provided"],
    ]
    meta_table = Table(meta_table_data, colWidths=[45 * mm, 110 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#4338ca")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 8 * mm))

    # Risk score banner
    score_table = Table(
        [[f"Risk Level: {risk_level}", f"Final Risk Score: {check_row['final_score']} / 100"]],
        colWidths=[77.5 * mm, 77.5 * mm],
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), risk_color),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 13),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 6 * mm))

    breakdown_data = [
        ["Signal", "Score"],
        ["ML text model (fraud probability)", f"{check_row['ml_probability']}%"],
        ["Rule-based red-flag score", f"{check_row['rule_score']}/100"],
        ["Company verification confidence", f"{check_row['company_confidence']}/100"],
    ]
    breakdown_table = Table(breakdown_data, colWidths=[110 * mm, 45 * mm])
    breakdown_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(breakdown_table)
    elements.append(Spacer(1, 8 * mm))

    flags = json.loads(check_row["flags_json"] or "[]")
    elements.append(Paragraph("Red Flags Detected", heading_style))
    if flags:
        for f in flags:
            elements.append(Paragraph(f"&bull; {f}", body_style))
    else:
        elements.append(Paragraph("No red-flag language patterns were detected in the posting text.", body_style))

    notes = json.loads(check_row["notes_json"] or "[]")
    elements.append(Paragraph("Company / Contact Verification Notes", heading_style))
    for n in notes:
        elements.append(Paragraph(f"&bull; {n}", body_style))

    recs = json.loads(check_row["recs_json"] or "[]")
    elements.append(Paragraph("Recommendations", heading_style))
    for r in recs:
        elements.append(Paragraph(f"&bull; {r}", body_style))

    elements.append(Spacer(1, 10 * mm))
    disclaimer = ParagraphStyle("Disclaimer", parent=body_style, fontSize=8, textColor=colors.grey)
    elements.append(Paragraph(
        "Disclaimer: This report is generated by an automated heuristic + machine learning system "
        "and is intended as a decision-support aid, not a definitive legal verdict. Always independently "
        "verify an employer before sharing personal information or making any payment.",
        disclaimer,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
